version: "3.8"

services:
  backend:
    image: zaidtalha123/backend:latest
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-net

  frontend:
    image: zaidtalha123/frontend:latest
    container_name: frontend
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend:5000
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
